services:
  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx/conf.d:ro
    ports:
      - 8080:80
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/themes:/var/www/html/wp-content/themes
    networks:
      - proxy

  db:
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - proxy

networks:
  proxy:

volumes:
  wordpress:
  db: