services:
  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx/conf.d:ro
    ports:
      - 8080:80
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress/wp.ini:/usr/local/etc/php/conf.d/wp.ini
    networks:
      - proxy

  db:
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - proxy

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  proxy:

volumes:
  db: